<?php
namespace AlumniCore\Includes;
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * AlumniCore standard SNS content settings.
 * Each enabled and configured SNS becomes a selectable system content item.
 */
class Social_SNS {
	const OPTION_NAME = 'alumni_core_sns_settings';
	const FACEBOOK_APP_ID = '185738782028798';
	const X = 'sns_x';
	const INSTAGRAM = 'sns_instagram';
	const FACEBOOK = 'sns_facebook';

	public static function services() {
		return array(
			self::X => array( 'label' => 'X', 'field_label' => 'X埋め込みコード' ),
			self::INSTAGRAM => array( 'label' => 'Instagram', 'field_label' => 'Instagram アカウントURL' ),
			self::FACEBOOK => array( 'label' => 'Facebook', 'field_label' => 'Facebook ページURL' ),
		);
	}

	public static function defaults() {
		$settings = array();
		foreach ( self::services() as $key => $service ) {
			$settings[ $key ] = array( 'enabled' => false, 'url' => '', 'embed_code' => '' );
		}
		return $settings;
	}

	public static function get_all() {
		$saved = get_option( self::OPTION_NAME, array() );
		$settings = wp_parse_args( is_array( $saved ) ? $saved : array(), self::defaults() );
		foreach ( self::services() as $key => $service ) {
			if ( ! isset( $settings[ $key ]['embed_code'] ) ) {
				$settings[ $key ]['embed_code'] = '';
			}
		}
		return $settings;
	}

	public static function save( array $input ) {
		$settings = self::defaults();
		foreach ( self::services() as $key => $service ) {
			$row = isset( $input[ $key ] ) && is_array( $input[ $key ] ) ? $input[ $key ] : array();
			$settings[ $key ]['enabled'] = ! empty( $row['enabled'] );

			if ( self::X === $key ) {
				$settings[ $key ]['embed_code'] = self::sanitize_x_embed_code( isset( $row['embed_code'] ) ? wp_unslash( $row['embed_code'] ) : '' );
				$settings[ $key ]['url'] = '';
			} else {
				$settings[ $key ]['url'] = esc_url_raw( isset( $row['url'] ) ? wp_unslash( $row['url'] ) : '' );
			}
		}
		update_option( self::OPTION_NAME, $settings );
		return $settings;
	}

	private static function sanitize_x_embed_code( $code ) {
		$allowed = array(
			'a' => array(
				'class'  => true,
				'href'   => true,
				'target' => true,
				'rel'    => true,
			),
			'script' => array(
				'async'   => true,
				'src'     => true,
				'charset' => true,
			),
		);
		$sanitized = wp_kses( (string) $code, $allowed );
		$sanitized = preg_replace( '/<script([^>]*?)src=["\']https:\/\/platform\.x\.com\/widgets\.js["\']([^>]*)><\/script>/i', '<script$1src="https://platform.x.com/widgets.js"$2></script>', $sanitized );
		return is_string( $sanitized ) ? trim( $sanitized ) : '';
	}

	public static function is_available( $key ) {
		$settings = self::get_all();
		if ( ! isset( $settings[ $key ] ) || empty( $settings[ $key ]['enabled'] ) ) {
			return false;
		}
		if ( self::X === $key ) {
			return ! empty( $settings[ $key ]['embed_code'] );
		}
		return ! empty( $settings[ $key ]['url'] );
	}

	public static function url( $key ) {
		$settings = self::get_all();
		return self::is_available( $key ) && isset( $settings[ $key ]['url'] ) ? (string) $settings[ $key ]['url'] : '';
	}

	public static function active_keys() {
		$keys = array();
		foreach ( array_keys( self::services() ) as $key ) {
			if ( self::is_available( $key ) ) $keys[] = $key;
		}
		return $keys;
	}

	public static function labels() {
		$labels = array();
		foreach ( self::services() as $key => $service ) $labels[ $key ] = $service['label'];
		return $labels;
	}

	public static function is_sns_key( $key ) {
		return array_key_exists( $key, self::services() );
	}

	/**
	 * Return provider-specific front-end markup for the SNS content window.
	 *
	 * X uses the official embed code generated by X Publish. Facebook uses
	 * its official public page plugin. Instagram account feeds do not have
	 * an equivalent simple profile-feed embed, so Core exposes a stable
	 * account window that can later be replaced through the filter.
	 *
	 * @param string $key
	 * @param array  $args Supported: height (px), title.
	 * @return string Safe HTML for direct front-end output.
	 */
	public static function render_embed( $key, array $args = array() ) {
		if ( ! self::is_available( $key ) ) {
			return '';
		}

		$settings = self::get_all();
		$url      = self::url( $key );
		$labels   = self::labels();
		$label    = isset( $labels[ $key ] ) ? $labels[ $key ] : '';
		$height   = isset( $args['height'] ) ? max( 240, min( 1200, absint( $args['height'] ) ) ) : 520;

		$html = '';

		switch ( $key ) {
			case self::X:
				$html = isset( $settings[ self::X ]['embed_code'] ) ? (string) $settings[ self::X ]['embed_code'] : '';
				break;

			case self::FACEBOOK:
				$facebook_width  = 340;
				$facebook_height = 720;
				$iframe_url = add_query_arg(
					array(
						'href'                  => $url,
						'tabs'                  => 'timeline',
						'width'                 => $facebook_width,
						'height'                => $facebook_height,
						'small_header'          => 'true',
						'adapt_container_width' => 'false',
						'hide_cover'            => 'true',
						'show_facepile'         => 'true',
						'appId'                 => self::FACEBOOK_APP_ID,
					),
					'https://www.facebook.com/plugins/page.php'
				);
				$html = sprintf(
					'<iframe class="alumni-sns-facebook-frame" src="%1$s" width="%2$d" height="540" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" title="%3$s"></iframe>',
					esc_url( $iframe_url ),
					$facebook_width,
					esc_attr( sprintf( __( '%s タイムライン', 'alumni-core' ), $label ) )
				);
				break;

			case self::INSTAGRAM:
				$html = sprintf(
					'<div class="alumni-sns-instagram-fallback"><div class="alumni-sns-instagram-fallback-icon" aria-hidden="true">◎</div><p class="alumni-sns-instagram-fallback-text">%1$s</p><a class="alumni-sns-instagram-fallback-button" href="%2$s" target="_blank" rel="noopener noreferrer">%3$s</a></div>',
					esc_html__( 'Instagramのアカウントページを表示します。', 'alumni-core' ),
					esc_url( $url ),
					esc_html__( 'Instagramを開く', 'alumni-core' )
				);
				break;
		}

		return (string) apply_filters( 'alumni_core_social_sns_embed_html', $html, $key, $url, $args );
	}
}
