<?php
/**
 * 役員・理事一覧グループの公開ページ.
 *
 * @package AlumniCore
 */

namespace AlumniCore\Includes;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Officer_List_Groups_Shortcode {

	const SHORTCODE = 'alumni_officer_list_group';
	const PAGE_ID_OPTION_PREFIX = 'alumni_core_officer_list_group_page_';

	public static function register() {
		add_shortcode( self::SHORTCODE, array( __CLASS__, 'render_shortcode' ) );
		if ( is_admin() ) {
			add_action( 'admin_init', array( __CLASS__, 'maybe_create_pages' ) );
		}
	}

	public static function maybe_create_pages() {
		foreach ( Officer_List_Groups::instance()->get_all() as $group ) {
			self::maybe_create_group_page( $group['group_id'], $group['name'] );
		}
	}

	private static function maybe_create_group_page( $group_id, $name ) {
		$option = self::PAGE_ID_OPTION_PREFIX . $group_id;
		$page_id = (int) get_option( $option, 0 );
		if ( $page_id && 'page' === get_post_type( $page_id ) ) {
			// Keep the auto-managed page title in sync with a group rename.
			// The group ID remains the permalink/shortcode key, so no member
			// binding or menu reference depends on the mutable display name.
			$page = get_post( $page_id );
			if ( $page && $page->post_title !== $name ) {
				wp_update_post(
					array(
						'ID'         => $page_id,
						'post_title' => $name,
					)
				);
			}
			return;
		}
		$slug = sanitize_title( 'officer-group-' . $name );
		if ( '' === $slug ) {
			$slug = 'officer-group-' . substr( $group_id, 0, 8 );
		}
		$existing = get_page_by_path( $slug, OBJECT, 'page' );
		if ( $existing instanceof \WP_Post ) {
			update_option( $option, (int) $existing->ID );
			return;
		}
		$new_id = wp_insert_post(
			array(
				'post_type' => 'page',
				'post_status' => 'publish',
				'post_title' => $name,
				'post_name' => $slug,
				'post_content' => '[' . self::SHORTCODE . ' id="' . $group_id . '"]',
			),
			true
		);
		if ( ! is_wp_error( $new_id ) && $new_id ) {
			update_option( $option, (int) $new_id );
		}
	}

	public static function get_group_url( $group_id ) {
		$group = Officer_List_Groups::instance()->get_group( $group_id );
		if ( null === $group ) {
			return '';
		}
		self::maybe_create_group_page( $group_id, $group['name'] );
		$page_id = (int) get_option( self::PAGE_ID_OPTION_PREFIX . $group_id, 0 );
		return $page_id && 'page' === get_post_type( $page_id ) ? (string) get_permalink( $page_id ) : '';
	}

	public static function render_shortcode( $atts ) {
		$atts = shortcode_atts( array( 'id' => '' ), (array) $atts, self::SHORTCODE );
		$group = Officer_List_Groups::instance()->get_group( (string) $atts['id'] );
		if ( null === $group ) {
			return '<p class="alumni-notice">' . esc_html__( 'この組織名簿グループは見つかりませんでした。', 'alumni-core' ) . '</p>';
		}
		$members = Officer_Lists::instance()->get_group_members( $group['group_id'] );
		ob_start();
		?>
		<div class="alumni-officer-list-group">
			<?php foreach ( $members as $index => $list ) : ?>
				<section class="alumni-officer-list-group-member">
					<h2><?php echo esc_html( $list['title'] ? $list['title'] : $list['name'] ); ?></h2>
					<?php echo Officers_Shortcode::render_list_shortcode( array( 'id' => $list['list_id'] ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- trusted shortcode HTML generated by Core. ?>
				</section>
			<?php endforeach; ?>
		</div>
		<?php
		return ob_get_clean();
	}
}
